commit_message: 'docs(i10n):[%language%] %original_file_name%'
append_commit_message: false

files:
  - source: /libs/*/*.md
    ignore:
      - /libs/*/*.*.md
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
  - source: /*.md
    ignore:
      - /*.*.md
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
  - source: integration/*.md
    ignore:
      - integration/*.*.md
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
  - source: /integration/*/*.md
    ignore:
      - /integration/*/*.*.md
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
