version: '3.8'

services:
  db:
    container_name: postgres-db-aiao-test
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      # - ./volumes/db/data:/var/lib/postgresql/data
      - ./volumes/db/init:/docker-entrypoint-initdb.d
